"""Scope B: student import code policy -- a row that supplies a Student ID keeps it (validated
for format/uniqueness); a row that leaves it blank gets one generated by student_code_seq at
commit time, same as normal creation. Documented in app/services/students_excel.py.
"""

import io

from openpyxl import Workbook

from app.db.scope import get_default_academy_id
from app.models.identity import User
from app.services import students_excel as excel_svc


def test_template_workbook_shows_student_code_as_optional(db_session):
    content = excel_svc.build_template_workbook()
    wb_bytes = io.BytesIO(content)
    from openpyxl import load_workbook

    wb = load_workbook(wb_bytes)
    ws = wb.active
    header = [c.value for c in next(ws.iter_rows(min_row=1, max_row=1))]
    assert any(cell.startswith("student_code:") for cell in header)
    # sample row demonstrates leaving it blank
    sample = [c.value for c in next(ws.iter_rows(min_row=2, max_row=2))]
    assert sample[0] in ("", None)


def test_preview_generates_no_error_for_blank_code(admin_client, db_session):
    academy_id = get_default_academy_id(db_session)
    rows = excel_svc.preview_import(db_session, academy_id, _xlsx_bytes([["", "طالب بدون كود", "", "", "", "academy", "active"]]), "import.xlsx")
    assert len(rows) == 1
    assert rows[0].errors == []
    assert rows[0].data["student_code"] is None


def test_preview_preserves_and_validates_provided_code(admin_client, db_session):
    academy_id = get_default_academy_id(db_session)
    rows = excel_svc.preview_import(db_session, academy_id, _xlsx_bytes([["TA-050001", "طالب بكود", "", "", "", "academy", "active"]]), "import.xlsx")
    assert rows[0].errors == []
    assert rows[0].data["student_code"] == "TA-050001"


def test_preview_rejects_duplicate_provided_code_in_same_file(admin_client, db_session):
    academy_id = get_default_academy_id(db_session)
    content = _xlsx_bytes([
        ["TA-050002", "طالب أول", "", "", "", "academy", "active"],
        ["TA-050002", "طالب ثاني", "", "", "", "academy", "active"],
    ])
    rows = excel_svc.preview_import(db_session, academy_id, content, "import.xlsx")
    assert rows[0].errors == []
    assert any("مكرر" in e for e in rows[1].errors)


def test_preview_rejects_code_already_in_db(admin_client, db_session):
    admin_client.post("/api/v1/admin/students", json={"full_name": "موجود بالفعل"})
    academy_id = get_default_academy_id(db_session)
    existing_code = admin_client.get("/api/v1/admin/students").json()["items"][0]["student_code"]
    rows = excel_svc.preview_import(db_session, academy_id, _xlsx_bytes([[existing_code, "طالب جديد", "", "", "", "academy", "active"]]), "import.xlsx")
    assert any("موجود بالفعل" in e for e in rows[0].errors)


def test_commit_generates_codes_for_blank_rows_and_keeps_provided_ones(admin_client, db_session):
    academy_id = get_default_academy_id(db_session)
    raw_rows = [
        {"student_code": "", "full_name": "طالب بدون كود"},
        {"student_code": "TA-050010", "full_name": "طالب بكود محدد"},
    ]
    admin_user = db_session.query(User).filter_by(email="admin@talent.dev").first()
    result = excel_svc.commit_import(db_session, academy_id, raw_rows, admin_user, None)
    assert len(result.created) == 2
    by_name = {c.full_name: c.student_code for c in result.created}
    assert by_name["طالب بكود محدد"] == "TA-050010"
    assert by_name["طالب بدون كود"] and by_name["طالب بدون كود"] != "TA-050010"
    import re

    assert re.fullmatch(r"TA-\d{6}", by_name["طالب بدون كود"])


def test_import_preview_and_commit_via_api_end_to_end(admin_client):
    content = _xlsx_bytes([["", "طالب API", "", "", "", "academy", "active"]])
    preview = admin_client.post(
        "/api/v1/admin/students/import/preview",
        files={"file": ("import.xlsx", content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")},
    )
    assert preview.status_code == 200, preview.text
    body = preview.json()
    assert body["valid_count"] == 1
    assert body["rows"][0]["data"]["student_code"] is None

    commit = admin_client.post("/api/v1/admin/students/import/commit", json={"rows": [r["data"] for r in body["rows"]]})
    assert commit.status_code == 200, commit.text
    created = commit.json()["created"]
    assert len(created) == 1
    import re

    assert re.fullmatch(r"TA-\d{6}", created[0]["student_code"])


def _xlsx_bytes(rows: list[list[str]]) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.append([f"{key}: {en} / {ar}" for key, en, ar, _ in excel_svc.COLUMNS])
    for row in rows:
        ws.append(row)
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
